"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ArrowRight, CloudSun, Plus, Shirt } from "lucide-react";
import { WorkspacePage } from "@/components/workspace-pages";

const api = process.env.NEXT_PUBLIC_API_URL ?? (process.env.NODE_ENV === "development" ? "http://localhost:8000/api/v1" : "/api/v1");

function PublicShell({ children }: { children: ReactNode }) {
  return <div className="public-shell"><header className="public-header"><Link href="/welcome" className="public-brand"><CloudSun size={22} /> WishWash</Link><nav><Link href="/about">About</Link><Link href="/how-it-works">How it works</Link><Link href="/login">Log in</Link><Link className="primary-button" href="/register">Get started</Link></nav></header>{children}<footer className="public-footer"><span>© WishWash</span><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/contact">Contact</Link></footer></div>;
}

function PublicContent({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return <PublicShell><main className="public-content"><span className="eyebrow">WISHWASH</span><h1>{title}</h1><p className="public-subtitle">{subtitle}</p><div className="public-body">{children}</div></main></PublicShell>;
}

export function LandingPage() { return <PublicShell><main className="landing-hero"><span className="eyebrow">WEATHER-SMART LAUNDRY PLANNING</span><h1>Never let rain ruin laundry day again.</h1><p>WishWash uses weather forecasts and drying conditions to help you choose when to wash, and alerts you when rain threatens clothes that are drying.</p><div className="landing-actions"><Link href="/register" className="primary-button">Get started <ArrowRight size={15} /></Link><Link href="/how-it-works" className="secondary-link">See how it works</Link></div><div className="landing-features"><Feature title="Smart recommendations" text="See the best drying windows in the forecast." /><Feature title="Rain alerts" text="Know when rain may interrupt a drying session." /><Feature title="Simple planning" text="Plan loads around your schedule and laundry type." /></div><Link href="/" className="text-link">Open dashboard →</Link></main></PublicShell>; }
function Feature({ title, text }: { title: string; text: string }) { return <article className="card feature-card"><CloudSun size={20} /><strong>{title}</strong><p>{text}</p></article>; }
export function AboutPage() { return <PublicContent title="About WishWash" subtitle="Laundry planning shaped around real weather."><p>WishWash helps people choose a better time to wash, estimate drying windows, and prepare when rain may threaten clothes left outside.</p><p>Forecasts are translated into clear guidance so you can decide what works for your household and schedule.</p></PublicContent>; }
export function HowItWorksPage() { return <PublicContent title="How WishWash works" subtitle="A simple decision from a complex forecast."><ol className="steps-list"><li><strong>Check the forecast.</strong> WishWash reviews rain, temperature, humidity, and wind.</li><li><strong>Choose a drying window.</strong> Recommendations estimate whether clothes can dry before rain.</li><li><strong>Plan your wash.</strong> Pick the suggested time or check any date yourself.</li><li><strong>Stay aware.</strong> Weather alerts can help you protect an active load when supported.</li></ol><Link className="primary-button" href="/recommendations">View recommendations <ArrowRight size={15} /></Link></PublicContent>; }
export function PrivacyPage() { return <PublicContent title="Privacy" subtitle="Use only the information needed to plan laundry around weather."><p>WishWash may use your chosen location to request local weather forecasts. In this preview, account, household, and laundry data are not connected to a production backend.</p><p>You can manage browser notification permission in your browser settings. Do not enter sensitive personal information into this preview.</p></PublicContent>; }
export function TermsPage() { return <PublicContent title="Terms of use" subtitle="Weather guidance is an estimate to support your decision."><p>Forecasts can change and drying times vary by fabric, load, shade, and ventilation. WishWash recommendations are informational and do not guarantee that laundry will dry or that rain will be detected.</p><p>You remain in control of when and how you wash and dry clothes.</p></PublicContent>; }
export function ContactPage() { const [sent, setSent] = useState(false); return <PublicContent title="Contact WishWash" subtitle="Send feedback about the planner."><form className="public-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><label>Name<input required /></label><label>Email<input required type="email" /></label><label>Message<textarea required rows={5} /></label><button className="primary-button">Send message</button>{sent && <p role="status">Thanks. Message sending is not connected in this preview.</p>}</form></PublicContent>; }

const authConfig = {
  login: { title: "Welcome back", subtitle: "Log in to continue planning laundry.", button: "Log in" },
  register: { title: "Create your account", subtitle: "Start planning laundry around your local weather.", button: "Create account" },
  "forgot-password": { title: "Reset your password", subtitle: "Enter your email and we’ll send reset instructions.", button: "Send reset link" },
  "reset-password": { title: "Choose a new password", subtitle: "Set a new password for your account.", button: "Update password" },
};
export function AuthPage({ mode }: { mode: keyof typeof authConfig }) { const [submitted, setSubmitted] = useState(false); const config = authConfig[mode]; return <PublicShell><main className="auth-card card"><Link href="/welcome" className="public-brand"><CloudSun size={22} /> WishWash</Link><h1>{config.title}</h1><p>{config.subtitle}</p><form className="public-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}>{mode !== "reset-password" && <label>Email<input type="email" required autoComplete="email" /></label>}{(mode === "login" || mode === "register") && <label>Password<input type="password" required minLength={8} autoComplete={mode === "login" ? "current-password" : "new-password"} /></label>}{mode === "reset-password" && <label>New password<input type="password" required minLength={8} autoComplete="new-password" /></label>}<button className="primary-button">{config.button}</button>{submitted && <p role="status">Authentication is not connected to a backend in this preview.</p>}</form><div className="auth-links">{mode === "login" ? <><Link href="/forgot-password">Forgot password?</Link><Link href="/register">Create account</Link></> : <Link href="/login">Back to log in</Link>}</div></main></PublicShell>; }

export function ActiveLaundryPage() { return <WorkspacePage title="Active laundry" subtitle="Monitor a load while it is drying."><section className="card workspace-panel"><div className="empty-session"><div className="empty-icon"><Shirt size={18} /></div><div><div className="empty-title">No active session saved</div><div className="empty-copy">The dashboard demo session is temporary and does not persist between pages.</div></div></div><Link href="/laundry" className="primary-button">Plan a laundry load <ArrowRight size={15} /></Link><p className="page-message">Background weather monitoring and push alerts are not connected in this preview.</p></section></WorkspacePage>; }
export function InventoryPage() { const [items, setItems] = useState([{ name: "Office clothes", count: 6 }, { name: "Daily clothes", count: 8 }]); const [name, setName] = useState(""); const [count, setCount] = useState(1); const add = (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setItems((current) => [...current, { name: name.trim(), count }]); setName(""); setCount(1); }; return <WorkspacePage title="Laundry inventory" subtitle="Track approximate clean clothing availability."><section className="card workspace-panel"><div className="inventory-list">{items.map((item, index) => <div className="inventory-row" key={`${item.name}-${index}`}><span><strong>{item.name}</strong><small>Approximate clean sets available</small></span><input aria-label={`${item.name} count`} type="number" min={0} value={item.count} onChange={(event) => setItems((current) => current.map((entry, i) => i === index ? { ...entry, count: Number(event.target.value) } : entry))} /></div>)}</div><form className="inventory-add" onSubmit={add}><input aria-label="New inventory category" placeholder="Add category" value={name} onChange={(event) => setName(event.target.value)} /><input aria-label="Number of sets" type="number" min={0} value={count} onChange={(event) => setCount(Number(event.target.value))} /><button className="primary-button"><Plus size={15} />Add item</button></form><p className="page-message">Inventory is stored only in this page session in the preview.</p></section></WorkspacePage>; }
export function ProfilePage() { const [saved, setSaved] = useState(false); return <WorkspacePage title="Profile" subtitle="Manage your WishWash account details."><section className="card workspace-panel"><form className="public-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><label>Name<input defaultValue="Guest" /></label><label>Email<input type="email" placeholder="you@example.com" /></label><button className="primary-button">Save profile</button>{saved && <p role="status">Profile saved for this session. Account storage is not connected.</p>}</form><Link href="/household" className="text-link">Manage household →</Link></section></WorkspacePage>; }
export function HouseholdPage() { const [members, setMembers] = useState(1); return <WorkspacePage title="Household settings" subtitle="Set up shared laundry preferences."><section className="card workspace-panel"><label className="field-label">Household name<input defaultValue="My household" /></label><label className="field-label">Household members<input type="number" min={1} max={20} value={members} onChange={(event) => setMembers(Number(event.target.value))} /></label><label className="field-label">Preferred drying method<select defaultValue="Outdoor line"><option>Outdoor line</option><option>Indoor rack</option><option>Dryer</option></select></label><p className="page-message">Household data is not saved to an account in this preview.</p></section></WorkspacePage>; }

type Recommendation = { status: string; reasons: string[]; drying_hours: number; rain_free_hours: number; rain_probability: number; drying_window_rain_probability: number; high: number; low: number; label: string };
export function RecommendationDetailPage() {
  const params = useParams<{ date: string }>();
  const [result, setResult] = useState<Recommendation | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch(`${api}/recommendations/evaluate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ latitude: 12.9716, longitude: 77.5946, date: params.date, start_time: "08:00", category: "Daily clothes" }) }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error?.message ?? "Recommendation is unavailable."); return data; }).then((data) => setResult(data.data)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Recommendation is unavailable.")); }, [params.date]);
  return <WorkspacePage title="Recommendation details" subtitle={`Weather reasoning for ${params.date}.`}><section className="card workspace-panel">{error ? <p className="page-message" role="status">{error}</p> : !result ? <p className="page-message">Checking forecast…</p> : <><span className={`status-pill ${result.status.toLowerCase()}`}>{result.status === "WASH" ? "GOOD TO WASH" : result.status}</span><div className="recommendation-meta"><Meta label="EXPECTED DRYING" value={`${result.drying_hours} hours`} /><Meta label="RAIN-FREE WINDOW" value={`${result.rain_free_hours} hours`} /><Meta label="RAIN RISK" value={`${result.drying_window_rain_probability}%`} /></div><h2>Why this day?</h2><ul className="detail-reasons">{result.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul><p className="page-message">Forecast rain probability: {result.rain_probability}%. Estimated high/low: {result.high}° / {result.low}°.</p><Link href={`/laundry?date=${params.date}`} className="primary-button">Plan this day <ArrowRight size={15} /></Link></>}<p><Link href="/recommendations" className="text-link">Back to recommendations</Link></p></section></WorkspacePage>;
}
function Meta({ label, value }: { label: string; value: string }) { return <div><div className="meta-label">{label}</div><div className="meta-value">{value}</div></div>; }
export function HistoryDetailPage() { const params = useParams<{ id: string }>(); return <WorkspacePage title="Laundry record" subtitle={`Record ${params.id}`}><section className="card workspace-panel"><p className="page-message">Laundry records are not persisted in this preview, so this record has no stored details.</p><Link href="/history" className="primary-button">Back to history</Link></section></WorkspacePage>; }
